package com.andrewq.planets.TvActivity;

import java.util.ArrayList;
import java.util.List;

public final class PlanetsList {
    public static final String MOVIE_CATEGORY[] = {
            "The Milky Way"
    };

    public static List<Planet> list;

    public static List<Planet> setupPlanets() {
        list = new ArrayList<Planet>();

        String title[] = {
                "Sun",
                "Mercury",
                "Venus",
                "Earth",
                "Mars",
                "Jupiter",
                "Saturn",
                "Uranus",
                "Neptune"
        };

        String description = "This is a test!";

        String bgImageUrl[] = {
                "http://amqtech.com/planets_pics/sun.jpg",
                "http://amqtech.com/planets_pics/mercury.jpg",
                "http://amqtech.com/planets_pics/venus.jpg",
                "http://amqtech.com/planets_pics/earth.jpg",
                "http://amqtech.com/planets_pics/mars.jpg",
                "http://amqtech.com/planets_pics/jupiter.jpg",
                "http://amqtech.com/planets_pics/saturn.jpg",
                "http://amqtech.com/planets_pics/uranus.jpg",
                "http://amqtech.com/planets_pics/neptune.jpg"
        };
        String cardImageUrl[] = {
                "http://amqtech.com/planets_pics/sun.jpg",
                "http://amqtech.com/planets_pics/mercury.jpg",
                "http://amqtech.com/planets_pics/venus.jpg",
                "http://amqtech.com/planets_pics/earth.jpg",
                "http://amqtech.com/planets_pics/mars.jpg",
                "http://amqtech.com/planets_pics/jupiter.jpg",
                "http://amqtech.com/planets_pics/saturn.jpg",
                "http://amqtech.com/planets_pics/uranus.jpg",
                "http://amqtech.com/planets_pics/neptune.jpg"
        };

        list.add(buildMovieInfo("category", title[0],
                "One million Earths could fit inside the Sun. If a hollow Sun was filled up with spherical Earths then around 960,000 would fit inside. On the other hand if these Earths were squished inside with no wasted space then around 1,300,000 would fit inside. The Suns surface area is 11,990 times that of the Earth’s.\\n\\nEventually, the Sun will consume the Earth. When all the Hydrogen has been burned, the Sun will continue for about 130 million more years, burning Helium, during which time it will expand to the point that it will engulf Mercury and Venus and the Earth. At this stage it will have become a red giant.\\n\\nThe Sun will one day be about the size of Earth. After its red giant phase, the Sun will collapse, retaining its enormous mass, but containing the approximate volume of our planet. When this happens, it will be called a white dwarf.\\n\\nThe Sun contains 99.86% of the mass in the Solar System. The mass of the Sun is approximately 330,000 times greater than that of Earth. It is almost three quarters Hydrogen, whilst most of the remaining mass is Helium.\\n\\nThe Sun is an almost perfect sphere. There is only a 10 kilometre difference in its polar diameter compared to its equatorial diameter. Considering the vast expanse of the Sun, this means it is the closest thing to a perfect sphere that has been observed in nature.\\n\\nLight from the Sun takes eight minutes to reach Earth. With a mean average distance of 150 million kilometres from Earth and with light travelling at 300,000 kilometres per second, dividing one by the other gives us an approximate time of 500 seconds, or eight minutes and 20 seconds. Although this energy reaches Earth in a few minutes, it will already have taken millions of years to travel from the Sun’s core to its surface.\\n\\nThe Sun travels at 220 kilometres per second. The Sun is 24,000–26,000 light years from the galactic centre and it takes the Sun 225-250 million years to complete an orbit of the centre of the Milky Way.\\n\\nThe distance from the Sun to Earth changes throughout the year. Because the Earth travels on an elliptical orbit around the Sun, the distance between the two bodies varies from 147 to 152 million kilometres. The distance between the Earth and the Sun is called an Astronomical Unit (AU).\\n\\nThe Sun is middle-aged. At around 4.5 billion years old, the Sun has already burned off about half of its store of Hydrogen. It has enough left to continue to burn Hydrogen for approximately another 5 billion years. The Sun is currently a type of star known as a Yellow Dwarf.\\n\\nThe Sun has a very strong magnetic field. Solar flares occur when magnetic energy is released by the Sun during magnetic storms, which we see as sunspots. In sunspots, the magnetic lines are twisted and they spin, much like a tornado would on Earth. The temperature inside the Sun can reach 15 million degrees Celsius.\\n\\nAt the Sun’s core, energy is generated by nuclear fusion, as Hydrogen converts to Helium. Because hot objects generally expand, the Sun would explode like a giant bomb if it weren’t for its enormous gravitational force.\\n\\nThe Sun generates solar wind. This is a stream of charged particles, which travels through the Solar System at approximately 450 kilometres per second. Solar wind occurs where the magnetic field of the Sun extends into space instead of following its surface.", "Star", cardImageUrl[0], bgImageUrl[0]));
        list.add(buildMovieInfo("category", title[1],
                description, "Planet", cardImageUrl[1], bgImageUrl[1]));
        list.add(buildMovieInfo("category", title[2],
                description, "Planet", cardImageUrl[2], bgImageUrl[2]));
        list.add(buildMovieInfo("category", title[3],
                description, "Planet", cardImageUrl[3], bgImageUrl[3]));
        list.add(buildMovieInfo("category", title[4],
                description, "Planet", cardImageUrl[4], bgImageUrl[4]));
        list.add(buildMovieInfo("category", title[5],
                description, "Planet", cardImageUrl[5], bgImageUrl[5]));
        list.add(buildMovieInfo("category", title[6],
                description, "Planet", cardImageUrl[6], bgImageUrl[6]));
        list.add(buildMovieInfo("category", title[7],
                description, "Planet", cardImageUrl[7], bgImageUrl[7]));
        list.add(buildMovieInfo("category", title[8],
                description, "Planet", cardImageUrl[8], bgImageUrl[8]));

        return list;
    }

    private static Planet buildMovieInfo(String category, String title,
                                         String description, String studio, String cardImageUrl,
                                         String bgImageUrl) {
        Planet planet = new Planet();
        planet.setId(Planet.getCount());
        Planet.incCount();
        planet.setTitle(title);
        planet.setDescription(description);
        planet.setStudio(studio);
        planet.setCategory(category);
        planet.setCardImageUrl(cardImageUrl);
        planet.setBackgroundImageUrl(bgImageUrl);
        return planet;
    }
}
